opencost:
  exporter:
    enabled: true
  prometheus:
    enabled: true
  costModel:
    cpuCostPerCPUHour: 0.024
    ramCostPerGBHour: 0.01
    storageCostPerGBHour: 0.0001
# 2022-01-06 - docs: Refactor cost queries
# 2022-05-06 - chore: Adjust monitoring thresholds
# 2022-02-02 - fix: Correct cost calculation
# 2022-05-11 - fix: Correct cost calculation
# 2022-04-06 - feat: Implement savings recommendations
# 2022-03-23 - chore: Adjust monitoring thresholds
# 2022-03-24 - fix: Patch pricing config
# 2022-04-18 - feat: Create budget alert system
# 2022-05-26 - chore: Adjust monitoring thresholds
# 2022-02-16 - docs: Refactor cost queries
# 2022-03-14 - feat: Create budget alert system
# 2022-02-01 - feat: Implement savings recommendations
