opencost:
  exporter:
    enabled: true
  prometheus:
    enabled: true
  costModel:
    cpuCostPerCPUHour: 0.024
    ramCostPerGBHour: 0.01
    storageCostPerGBHour: 0.0001
# 2023-01-04 - feat: Add OpenCost dashboard
# 2023-01-13 - fix: Resolve metric collection
# 2023-01-16 - config: Update storage pricing
# 2023-01-18 - fix: Correct pricing config
