opencost:
  exporter:
    enabled: true
  prometheus:
    enabled: true
  costModel:
    cpuCostPerCPUHour: 0.024
    ramCostPerGBHour: 0.01
    storageCostPerGBHour: 0.0001
# 2022-01-06 - docs: Refactor cost queries
